---
title: "new_benchmarking"
output:
  pdf_document: default
  html_document: default
date: "2023-07-21"
---

This code is not pretty - it was meant to be done quickly.
# This was not used in the paper, but has some R code to generate plots for an older version of the preprint. Plots on the paper used the provided python code.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{R}
library(ggplot2)
library(dplyr)
library(scales)
library(patchwork)
library(stringr)


plotSavePath = "~/vscode/IVSparse-Figures/plots/"

largeEigenResults10 = read.csv("~/results/EigenResults_0.1_large.csv")
largeVCSCResults10 = read.csv("~/results/VCSCResults_0.1_large.csv")
largeIVCSCResults10 = read.csv("~/results/IVCSCResults_0.1_large.csv")

eigenResults1 = read.csv("~/results/EigenResults_0.01.csv")
VCSCResults1 = read.csv("~/results/VCSCResults_0.01.csv")
IVCSCResults1 = read.csv("~/results/IVCSCResults_0.01.csv")

eigenResults5 = read.csv("~/results/EigenResults_0.05.csv")
VCSCResults5 = read.csv("~/results/VCSCResults_0.05.csv")
IVCSCResults5 = read.csv("~/results/IVCSCResults_0.05.csv")

eigenResults10 = read.csv("~/results/EigenResults_0.1.csv")
VCSCResults10 = read.csv("~/results/goodresults/VCSCResults_0.1.csv")
IVCSCResults10 = read.csv("~/results/goodresults/IVCSCResults_0.1.csv")

density_VCSCResults10 = read.csv("~/results/density_VCSCResults_0.1.csv")
density_IVCSCResults10 = read.csv("~/results/density_IVCSCResults_0.1.csv")
density_eigenResults10 = read.csv("~/results/density_EigenResults_0.1.csv")


# 
# # Function to plot the ratio of dataset over Eigen
# plot_ratio_over_eigen <- function(dataset_results, dataset_name, y_axis_variable, eigenResults) {
#   # Select the first data point for each ID in eigenResults and dataset_results
# 
#   eigen_first_data <- eigenResults %>%
#     group_by(ID) %>%
#     summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
#   
#   
#   dataset_first_data <- dataset_results %>%
#     group_by(ID) %>%
#     summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
#   
#   
#   # Calculate the ratio by dividing y_axis_variable in dataset_results by the corresponding values in eigen_first_data
#   ratio <- dataset_first_data[[y_axis_variable]] / eigen_first_data[[y_axis_variable]]
#   
#   # Create a new data frame with redundancy and ratio
#   combined_data <- data.frame(redundancy = eigen_first_data$redundancy, ratio = ratio)
#   
#   # Get the indices of the minimum and maximum ratio values
#   min_index <- which.min(ratio)
#   max_index <- which.max(ratio)
#   
#   # Create the scatter plot for the dataset ratio over Eigen
#   p <- ggplot(combined_data, aes(x = redundancy, y = ratio)) +
#     geom_point() +
#     geom_text(data = combined_data[c(min_index, max_index), ],
#               aes(label = round(ratio, 2),
#                   vjust = ifelse(ratio[min_index] < ratio[max_index], 1.5, -0.5),
#                   color = "blue",  # Set the text color to blue
#                   fontface = "bold",  # Make the text bold
#                   size = 4),  # Set the text size slightly bigger
#               show.legend = FALSE) +
#     labs(title = paste0(toupper(dataset_name), " Ratio of ", toupper(y_axis_variable), " over Eigen"),
#          x = "Redundancy",
#          y = paste0(toupper(dataset_name), " / Eigen Ratio")) +
#     theme_minimal()
#   
#   # Count the number of markers (data points)
#   num_markers <- nrow(combined_data)
#   p <- p + geom_hline(yintercept = 1, linetype = "dashed")
# 
#   print(p)
# }
# 
# 
# 
# plot_ratio_over_eigen(VCSCResults, "VCSC", "constructor_time")
# plot_ratio_over_eigen(IVCSCResults, "IVCSC", "constructor_time")
# plot_ratio_over_eigen(VCSCResults, "VCSC", "scalar_time")
# plot_ratio_over_eigen(IVCSCResults, "IVCSC", "scalar_time")
# plot_ratio_over_eigen(VCSCResults, "VCSC", "spmv_time")
# plot_ratio_over_eigen(IVCSCResults, "IVCSC", "spmv_time")
# plot_ratio_over_eigen(VCSCResults, "VCSC", "spmm_time")
# plot_ratio_over_eigen(IVCSCResults, "IVCSC", "spmm_time")

```


## **Averages of Data at 5% Density**


```{R}
# Load the necessary libraries
# Load the necessary libraries
library(ggplot2)

# Read the data from CSV files (if not already loaded)
# eigenResults = read.csv("~/results/EigenResults.csv")
# VCSCResults = read.csv("~/results/VCSCResults.csv")
# IVCSCResults = read.csv("~/results/IVCSCResults.csv")

# Load required library
library(ggplot2)
library(dplyr)



# # Create the function with data averaging
# create_scatter_plot <- function(data, dataset_name, y_col) {
#   # Group data by IDs and calculate the average values for the specified columns
#   averaged_data <- data %>%
#     group_by(ID) %>%
#     summarise_at(vars(redundancy, y_col), ~mean(., na.rm = TRUE))
# 
#   # Create the scatter plot using the averaged data
#   ggplot(averaged_data, aes_string(x = "redundancy", y = y_col)) +
#     geom_point(color = "blue") +
#     labs(title = paste(dataset_name, "-", y_col), x = "Redundancy", y = y_col) +
#     theme_minimal()
# }
# # Example usage:
# # Assuming you have data frames 'eigenResults', 'VCSCResults', 'IVCSCResults' with columns 'ID', 'redundancy', and 'spmm_time'
# 
# scatter_eigenResults <- create_scatter_plot(eigenResults5, "Eigen" , "size" )
# scatter_VCSCResults <- create_scatter_plot(VCSCResults5, "VCSC", "size")
# scatter_IVCSCResults <- create_scatter_plot(IVCSCResults5, "IVCSC","size")
# print(scatter_eigenResults)
# print(scatter_VCSCResults)
# print(scatter_IVCSCResults)
# 
# scatter_eigenResults <- create_scatter_plot(eigenResults5, "Eigen" , "constructor_time" )
# scatter_VCSCResults <- create_scatter_plot(VCSCResults5, "VCSC", "constructor_time")
# scatter_IVCSCResults <- create_scatter_plot(IVCSCResults5, "IVCSC","constructor_time")
# print(scatter_eigenResults)
# print(scatter_VCSCResults)
# print(scatter_IVCSCResults)
# 
# scatter_eigenResults <- create_scatter_plot(eigenResults5, "Eigen" , "scalar_time" )
# scatter_VCSCResults <- create_scatter_plot(VCSCResults5, "VCSC", "scalar_time")
# scatter_IVCSCResults <- create_scatter_plot(IVCSCResults5, "IVCSC","scalar_time")
# print(scatter_eigenResults)
# print(scatter_VCSCResults)
# print(scatter_IVCSCResults)
# 
# 
# scatter_eigenResults <- create_scatter_plot(eigenResults5, "Eigen" , "spmv_time" )
# scatter_VCSCResults <- create_scatter_plot(VCSCResults5, "VCSC", "spmv_time")
# scatter_IVCSCResults <- create_scatter_plot(IVCSCResults5, "IVCSC","spmv_time")
# print(scatter_eigenResults)
# print(scatter_VCSCResults)
# print(scatter_IVCSCResults)
# 
# scatter_eigenResults <- create_scatter_plot(eigenResults5, "Eigen" , "spmm_time" )
# scatter_VCSCResults <- create_scatter_plot(VCSCResults5, "VCSC", "spmm_time")
# scatter_IVCSCResults <- create_scatter_plot(IVCSCResults5, "IVCSC","spmm_time")
# print(scatter_eigenResults)
# print(scatter_VCSCResults)
# print(scatter_IVCSCResults)

```
## **Averages of Data at 10% Density**

```{R}

# scatter_eigenResults <- create_scatter_plot(eigenResults10, "Eigen" , "spmm_time" )
# scatter_VCSCResults <- create_scatter_plot(VCSCResults10, "VCSC", "spmm_time")
# scatter_IVCSCResults <- create_scatter_plot(IVCSCResults10, "IVCSC","spmm_time")
# print(scatter_eigenResults)
# print(scatter_VCSCResults)
# print(scatter_IVCSCResults)
# 
# scatter_eigenResults <- create_scatter_plot(eigenResults10, "Eigen" , "spmv_time" )
# scatter_VCSCResults <- create_scatter_plot(VCSCResults10, "VCSC", "spmv_time")
# scatter_IVCSCResults <- create_scatter_plot(IVCSCResults10, "IVCSC","spmv_time")
# print(scatter_eigenResults)
# print(scatter_VCSCResults)
# print(scatter_IVCSCResults)
# 
# scatter_eigenResults <- create_scatter_plot(eigenResults10, "Eigen" , "scalar_time" )
# scatter_VCSCResults <- create_scatter_plot(VCSCResults10, "VCSC", "scalar_time")
# scatter_IVCSCResults <- create_scatter_plot(IVCSCResults10, "IVCSC","scalar_time")
# print(scatter_eigenResults)
# print(scatter_VCSCResults)
# print(scatter_IVCSCResults)
# 
# scatter_eigenResults <- create_scatter_plot(eigenResults10, "Eigen" , "constructor_time" )
# scatter_VCSCResults <- create_scatter_plot(VCSCResults10, "VCSC", "constructor_time")
# scatter_IVCSCResults <- create_scatter_plot(IVCSCResults10, "IVCSC","constructor_time")
# print(scatter_eigenResults)
# print(scatter_VCSCResults)
# print(scatter_IVCSCResults)
# 
# scatter_eigenResults <- create_scatter_plot(eigenResults10, "Eigen" , "size" )
# scatter_VCSCResults <- create_scatter_plot(VCSCResults10, "VCSC", "size")
# scatter_IVCSCResults <- create_scatter_plot(IVCSCResults10, "IVCSC","size")
# print(scatter_eigenResults)
# print(scatter_VCSCResults)
# print(scatter_IVCSCResults)


```


## **Dual Plots Between 5% and 10% Density as a Ratio Over Eigen**


```{R}


format_y_axis_label <- function(y_axis_variable) {
  # Split the y-axis variable by underscores
  words <- strsplit(y_axis_variable, "_")[[1]]
  
  # Check the number of words after splitting
  num_words <- length(words)
  
  if (num_words == 2) {
    if (words[1] == "spmv") {
      formatted_label <- "SpMV Time"
    } else if (words[1] == "spmm") {
      formatted_label <- "SpMM Time"
    } else {
      formatted_label <- tools::toTitleCase(paste(words, collapse = " "))
    }
  } else {
    formatted_label <- tools::toTitleCase(y_axis_variable)
  }
  
  
  return(formatted_label)
}

triple_plot_ratio_over_eigen_no_legend <- function(dataset1_results, dataset1_name, dataset2_results, dataset2_name, dataset3_results, dataset3_name, eigen1, eigen2, eigen3, y_axis_variable, name) {
  # Step 1: Call the pdf command to start the plot
    
    dir.create(file.path(paste0("~/vscode/IVSparse-Figures/plots/",name)), showWarnings = FALSE)
    path <- paste0("~/vscode/IVSparse-Figures/plots/",name,"/",y_axis_variable,".pdf")

    pdf(file <- path,  
    width = 6, # The width of the plot in inches
    height = 7) # The height of the plot in inches
  
  # Select the first data point for each ID in eigenResults5, eigenResults10, and eigenResults3
  eigen_first_data_1 <- eigen1 %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  eigen_first_data_2 <- eigen2 %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  eigen_first_data_3 <- eigen3 %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  dataset1_first_data <- dataset1_results %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  dataset2_first_data <- dataset2_results %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  dataset3_first_data <- dataset3_results %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  # Calculate the ratio by dividing y_axis_variable in dataset1_results by the corresponding values in eigen_first_data_5
  ratio1 <- dataset1_first_data[[y_axis_variable]] / eigen_first_data_1[[y_axis_variable]]
  
  # Calculate the ratio by dividing y_axis_variable in dataset2_results by the corresponding values in eigen_first_data_10
  ratio2 <- dataset2_first_data[[y_axis_variable]] / eigen_first_data_2[[y_axis_variable]]
  
  # Calculate the ratio by dividing y_axis_variable in dataset3_results by the corresponding values in eigen_first_data_3
  ratio3 <- dataset3_first_data[[y_axis_variable]] / eigen_first_data_3[[y_axis_variable]]
  
  # Combine the data frames for all three datasets and eigenResults
  combined_data <- rbind(
    data.frame(redundancy = dataset1_first_data$redundancy, ratio = ratio1, dataset = dataset1_name, eigenResult = "eigen1"),
    data.frame(redundancy = dataset2_first_data$redundancy, ratio = ratio2, dataset = dataset2_name, eigenResult = "eigen2"),
    data.frame(redundancy = dataset2_first_data$redundancy, ratio = ratio3, dataset = dataset3_name, eigenResult = "eigen3")
  )

  # Convert the dataset variable to a factor and set custom levels to control the order of appearance
  combined_data$dataset <- factor(combined_data$dataset, levels = c(dataset1_name, dataset2_name, dataset3_name))
  combined_data$ratio <- with(combined_data, ratio[order(dataset)])
  
    # if (grepl("All", name, ignore.case = TRUE)) {
    #   name <- ""
    #   legend_name <- "Format"
    # 
    # } else {
    #   name <- paste0(name, " ")
    #   legend_name <- "Density"
    # }
  

  # Create the scatter plot for the dataset ratio over Eigen
p <- ggplot(combined_data, aes(x = redundancy, y = ratio, color = dataset, shape = dataset)) +
    geom_point() +
    labs(x = "Mean Matrix Redundancy",
         y = paste0("Ratio of ", format_y_axis_label(y_axis_variable), " Over Eigen")) +
    theme_minimal() +
    theme(axis.title.y = element_text(size = 18),
          axis.title.x = element_text(size = 18),
          axis.text = element_text(size = 18),
          legend.position = "none") +  # Remove the legend
    scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 5)) +
    scale_color_manual(values = c("#00C058", "#BF00F1", "#0000EE"),
                       labels = c(dataset1_name, dataset2_name, dataset3_name),
                       guide = guide_legend(override.aes = list(shape = NA, size = NA)),
                       name = element_text(color = "white")) +  # Set legend text color
    scale_shape_manual(values = c(16, 17, 15),
                       labels = c(dataset1_name, dataset2_name, dataset3_name),
                       guide = guide_legend(override.aes = list(color = NA, size = NA)),
                       name = element_text(color = "white")) +  # Set legend text color
    theme( # All legend colors is made white as to be invisible. This keep spacing for when there is a legend present -> all plots have same dimension/layout
      legend.direction = "horizontal", 
      legend.text.align = 0.5, 
      legend.position = "bottom", 
      legend.spacing.x = unit(0.5, "mm"),
      legend.text = element_text(size = 18, color = "white"),  # Set legend text color
      legend.title = element_text(size = 18, color = "white"))  # Set legend title color



    # theme(
    #   legend.direction = "horizontal", 
    #   legend.text.align = 0.5, 
    #   legend.position = "bottom", 
    #   legend.spacing.x = unit(0.5, "mm"))
  

  
  
  # Add a label "1.0" on the y-axis at y=1
  p <- p + geom_hline(yintercept = 1, linetype = "dashed", color = "blue") 

  # Count the number of markers (data points)
  num_markers <- nrow(combined_data)
  cat("Number of markers:", num_markers, "\n")

  # # Set colors and labels for the legend using scale_color_manual
  # p <- p + scale_color_manual(values = c("purple", "green", "blue"), labels = c(dataset1_name, dataset2_name, dataset3_name), name = "Format")
  # p <- p + scale_shape_manual(values = c(16, 17, 15), labels = c(dataset1_name, dataset2_name, dataset3_name), name = "Format")
  # 

  # Count the number of markers (data points)
  num_markers <- nrow(combined_data)
  cat("Number of markers:", num_markers, "\n")

  # Define custom dataset names for the legend
  # dataset_names <- c(dataset1_name, dataset2_name, dataset3_name)

  # Set colors and labels for the legend using scale_color_manual
  # p <- p + scale_color_manual(values = c("purple", "green", "blue"), labels = dataset_names)

  # Print the final plot
  print(p)
  dev.off()
}
triple_plot_ratio_over_eigen_no_legend(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"spmv_time","All_10_density")

```

```{R}
triple_plot_ratio_over_eigen_bottom_legend <- function(dataset1_results, dataset1_name, dataset2_results, dataset2_name, dataset3_results, dataset3_name, eigen1, eigen2, eigen3, y_axis_variable, name) {
  # Step 1: Call the pdf command to start the plot
    
    dir.create(file.path(paste0("~/vscode/IVSparse-Figures/plots/",name)), showWarnings = FALSE)
    path <- paste0("~/vscode/IVSparse-Figures/plots/",name,"/",y_axis_variable,".pdf")

    pdf(file <- path,  
    width = 6, # The width of the plot in inches
    height = 7) # The height of the plot in inches
  
  # Select the first data point for each ID in eigenResults5, eigenResults10, and eigenResults3
  eigen_first_data_1 <- eigen1 %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  eigen_first_data_2 <- eigen2 %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  eigen_first_data_3 <- eigen3 %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  dataset1_first_data <- dataset1_results %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  dataset2_first_data <- dataset2_results %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  dataset3_first_data <- dataset3_results %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  # Calculate the ratio by dividing y_axis_variable in dataset1_results by the corresponding values in eigen_first_data_5
  ratio1 <- dataset1_first_data[[y_axis_variable]] / eigen_first_data_1[[y_axis_variable]]
  
  # Calculate the ratio by dividing y_axis_variable in dataset2_results by the corresponding values in eigen_first_data_10
  ratio2 <- dataset2_first_data[[y_axis_variable]] / eigen_first_data_2[[y_axis_variable]]
  
  # Calculate the ratio by dividing y_axis_variable in dataset3_results by the corresponding values in eigen_first_data_3
  ratio3 <- dataset3_first_data[[y_axis_variable]] / eigen_first_data_3[[y_axis_variable]]
  
  # Combine the data frames for all three datasets and eigenResults
  combined_data <- rbind(
    data.frame(redundancy = dataset1_first_data$redundancy, ratio = ratio1, dataset = dataset1_name, eigenResult = "eigen1"),
    data.frame(redundancy = dataset2_first_data$redundancy, ratio = ratio2, dataset = dataset2_name, eigenResult = "eigen2"),
    data.frame(redundancy = dataset3_first_data$redundancy, ratio = ratio3, dataset = dataset3_name, eigenResult = "eigen3")
  )

  # Convert the dataset variable to a factor and set custom levels to control the order of appearance
  combined_data$dataset <- factor(combined_data$dataset, levels = c(dataset1_name, dataset2_name, dataset3_name))
  combined_data$ratio <- with(combined_data, ratio[order(dataset)])
  
    if (grepl("All", name, ignore.case = TRUE)) {
      name <- ""
      legend_name <- "Format"
    
    } else {
      name <- paste0(name, " ")
      legend_name <- "Density"
    }
  

  # Create the scatter plot for the dataset ratio over Eigen
p <- ggplot(combined_data, aes(x = redundancy, y = ratio, color = dataset, shape = dataset)) +
    geom_point() +
    labs(x = "Mean Matrix Redundancy",
         y = paste0("Ratio of ", format_y_axis_label(y_axis_variable), " Over Eigen")) +
    theme_minimal() +
    theme(axis.title.y = element_text(size = 18),
          axis.title.x = element_text(size = 18),
          axis.text = element_text(size = 18),
          legend.text = element_text(size = 18),    # Adjust the font size of legend labels
          legend.title = element_text(size = 18)) +  # Adjust the font size here
    scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 5)) +
    scale_color_manual(values = c("#00C058", "#BF00F1", "#0000EE"), 
                       labels = c(dataset1_name, dataset2_name, dataset3_name), 
                       name = legend_name,
                       guide = guide_legend(override.aes = list(size = 4))) +  # Increase symbol size
    scale_shape_manual(values = c(16, 17, 15), 
                       labels = c(dataset1_name, dataset2_name, dataset3_name), 
                       name = legend_name,
                       guide = guide_legend(override.aes = list(size = 6))) +  # Increase symbol size
    theme(
      legend.direction = "horizontal", 
      legend.text.align = 0.5, 
      legend.position = "bottom", 
      legend.spacing.x = unit(0.5, "mm"),
      legend.text = element_text(size = 18))

  
  
  # Add a label "1.0" on the y-axis at y=1
  p <- p + geom_hline(yintercept = 1, linetype = "dashed", color = "blue") 

  # Count the number of markers (data points)
  num_markers <- nrow(combined_data)
  cat("Number of markers:", num_markers, "\n")

  # # Set colors and labels for the legend using scale_color_manual
  # p <- p + scale_color_manual(values = c("purple", "green", "blue"), labels = c(dataset1_name, dataset2_name, dataset3_name), name = "Format")
  # p <- p + scale_shape_manual(values = c(16, 17, 15), labels = c(dataset1_name, dataset2_name, dataset3_name), name = "Format")
  # 

  # Count the number of markers (data points)
  num_markers <- nrow(combined_data)
  cat("Number of markers:", num_markers, "\n")

  # Define custom dataset names for the legend
  dataset_names <- c(dataset1_name, dataset2_name, dataset3_name)

  # Set colors and labels for the legend using scale_color_manual
  # p <- p + scale_color_manual(values = c("purple", "green", "blue"), labels = dataset_names)

  # Print the final plot
  print(p)
  dev.off()
}
triple_plot_ratio_over_eigen_bottom_legend(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"spmv_time","All_10_density")

```


```{R}


triple_plot_raw <- function(dataset1_results, dataset1_name, dataset2_results, dataset2_name, dataset3_results, dataset3_name, eigen1, eigen2, eigen3, y_axis_variable, name) {
  # Step 1: Call the pdf command to start the plot
    
    dir.create(file.path(paste0("~/vscode/IVSparse-Figures/plots/",name)), showWarnings = FALSE)
    # path <- paste0("~/vscode/IVSparse-Figures/plots/",name,"/","raw_",y_axis_variable,".pdf")
    path <- paste0("~/vscode/IVSparse-Figures/plots/",name,"/","raw_",y_axis_variable,".png")

    # png(file <- path,  
    # width = 6, # The width of the plot in inches
    # height = 6) # The height of the plot in inches
    
    png(filename = path,
        width = 6,
        height = 6,
        units = "in",
        res = 576 * 2
        # type = "Xlib"
        )
  
  # Select the first data point for each ID in eigenResults5, eigenResults10, and eigenResults3
  eigen_first_data_1 <- eigen1 %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  eigen_first_data_2 <- eigen2 %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  eigen_first_data_3 <- eigen3 %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  dataset1_first_data <- dataset1_results %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  dataset2_first_data <- dataset2_results %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  dataset3_first_data <- dataset3_results %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~mean(., na.rm = TRUE))
  
  # Calculate the ratio by dividing y_axis_variable in dataset1_results by the corresponding values in eigen_first_data_5
  ratio1 <- dataset1_first_data[[y_axis_variable]] / 10e+6
  
  # Calculate the ratio by dividing y_axis_variable in dataset2_results by the corresponding values in eigen_first_data_10
  ratio2 <- dataset2_first_data[[y_axis_variable]] / 10e+6
  
  # Calculate the ratio by dividing y_axis_variable in dataset3_results by the corresponding values in eigen_first_data_3
  ratio3 <- dataset3_first_data[[y_axis_variable]] / 10e+6
  
  # Combine the data frames for all three datasets and eigenResults
  combined_data <- rbind(
    data.frame(redundancy = dataset1_first_data$redundancy, ratio = ratio1, dataset = dataset1_name, eigenResult = "eigen1"),
    data.frame(redundancy = dataset2_first_data$redundancy, ratio = ratio2, dataset = dataset2_name, eigenResult = "eigen2"),
    data.frame(redundancy = dataset3_first_data$redundancy, ratio = ratio3, dataset = dataset3_name, eigenResult = "eigen3")
  )

  # Convert the dataset variable to a factor and set custom levels to control the order of appearance
  combined_data$dataset <- factor(combined_data$dataset, levels = c(dataset1_name, dataset2_name, dataset3_name))
  combined_data$ratio <- with(combined_data, ratio[order(dataset)])
  
    if (grepl("All", name, ignore.case = TRUE)) {
      name <- ""
      legend_name <- "Format"
    
    } else {
      name <- paste0(name, " ")
      legend_name <- "Density"
    }
# Create the scatter plot for the dataset ratio over Eigen
p <- ggplot(combined_data, aes(x = redundancy, y = ratio, color = dataset, shape = dataset)) +
  geom_point() +
  labs(x = "Mean Matrix Redundancy",
       y = paste0(format_y_axis_label(y_axis_variable), " (ms)")) +
  theme_minimal() +
  theme(axis.title.y = element_text(size = 18),
        axis.title.x = element_text(size = 18),
        axis.text = element_text(size = 18),
        legend.text = element_text(size = 18),    # Adjust the font size of legend labels
        legend.title = element_text(size = 18)) +  # Adjust the font size here
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  scale_color_manual(values = c("#00C058", "#BF00F1", "#0000EE"),
                     labels = c(dataset1_name, dataset2_name, dataset3_name),
                     breaks = c(dataset1_name, dataset2_name, dataset3_name),  # Set the breaks for the legend
                     guide = guide_legend(override.aes = list(size = 3), title = "Format: "),
                     name = element_text(color = "black")) +  # Set legend text color
  scale_shape_manual(values = c(16, 17, 15),
                     labels = c(dataset1_name, dataset2_name, dataset3_name),
                     breaks = c(dataset1_name, dataset2_name, dataset3_name),  # Set the breaks for the legend
                     guide = guide_legend(override.aes = list(size = 3), title = "Format: "),
                     name = element_text(color = "black")) +  # Set legend text color
  theme( # All legend colors are made white as to be invisible. This keeps spacing for when there is a legend present -> all plots have the same dimension/layout
    legend.direction = "horizontal", 
    legend.text.align = 0.5, 
    legend.position = "bottom", 
    legend.spacing.x = unit(0.5, "mm"),
    legend.text = element_text(size = 18, color = "black"),  # Set legend text color
    legend.title = element_text(size = 18, color = "black"))  # Set legend title color

  
  
  # Add a label "1.0" on the y-axis at y=1
  # p <- p + geom_hline(yintercept = 1, linetype = "dashed", color = "blue") 

  # Count the number of markers (data points)
  num_markers <- nrow(combined_data)
  cat("Number of markers:", num_markers, "\n")

  # # Set colors and labels for the legend using scale_color_manual
  # p <- p + scale_color_manual(values = c("purple", "green", "blue"), labels = c(dataset1_name, dataset2_name, dataset3_name), name = "Format")
  # p <- p + scale_shape_manual(values = c(16, 17, 15), labels = c(dataset1_name, dataset2_name, dataset3_name), name = "Format")
  # 

  # Count the number of markers (data points)
  num_markers <- nrow(combined_data)
  cat("Number of markers:", num_markers, "\n")

  # Define custom dataset names for the legend
  dataset_names <- c(dataset1_name, dataset2_name, dataset3_name)

  # Set colors and labels for the legend using scale_color_manual
  # p <- p + scale_color_manual(values = c("purple", "green", "blue"), labels = dataset_names)

  # Print the final plot
  print(p)
  dev.off()
}
# VCSCResults102 = read.csv("~/IVSparse/Benchmarking/results/VCSCResults_CSC.csv")
# eigenResults102 = read.csv("~/IVSparse/Benchmarking/results/EigenResults_CSC.csv")
# IVCSCResults102 = read.csv("~/IVSparse/Benchmarking/results/IVCSCResults_CSC.csv")

# VCSCResults102 = read.csv("~/resultsSPMV/VCSCResults_CSC.csv")
# eigenResults102 = read.csv("~/resultsSPMV/EigenResults_CSC.csv")
# IVCSCResults102 = read.csv("~/resultsSPMV/IVCSCResults_CSC.csv")

# triple_plot_raw(IVCSCResults102, "IVCSC", VCSCResults102, "VCSC", eigenResults102, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"scalar_time","new2_All_10_density")
# triple_plot_raw(IVCSCResults102, "IVCSC", VCSCResults102, "VCSC", eigenResults102, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"spmv_time","new2_All_10_density")
# triple_plot_raw(IVCSCResults102, "IVCSC", VCSCResults102, "VCSC", eigenResults102, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"spmm_time","new2_All_10_density")
# triple_plot_raw(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"constructor_time","new2_All_10_density")
# triple_size_plot(IVCSCResults102, "IVCSC",  VCSCResults102, "VCSC", eigenResults102, "CSC" , eigenResults102, eigenResults102, eigenResults102 ,"new2_All_10_density")
# triple_plot_raw(IVCSCResults102, "IVCSC", VCSCResults102, "VCSC", eigenResults102, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"iterator_time","new2_All_10_density")
# triple_size_plot(IVCSCResults102, "IVCSC",  VCSCResults102, "VCSC", eigenResults102, "CSC" , eigenResults102, eigenResults102, eigenResults102 ,"new2_All_10_density")
# density_triple_size_plot(density_IVCSCResults10, "IVCSC",  density_VCSCResults10, "VCSC", density_eigenResults10, "CSC" ,"raw_All_10_density")

# triple_plot_raw(VCSCResults1, "1%", VCSCResults5, "5%", VCSCResults10, "10%", eigenResults1, eigenResults5, eigenResults10, "constructor_time", "VCSC")

```

```{R}


triple_size_plot <- function(dataset1_results, dataset1_name, dataset2_results, dataset2_name, dataset3_results, dataset3_name, eigenResults1, eigenResults5, eigenResults10, name) {
  
  y_axis_variable <- "size"
  firstNonzero <- eigenResults1[1, "nonzeros"]
  secondNonzero <- eigenResults5[1, "nonzeros"]
  thirdNonzero <- eigenResults10[1, "nonzeros"]
    
    dir.create(file.path(paste0("~/vscode/IVSparse-Figures/plots/",name)), showWarnings = FALSE)
    # path <- paste0("~/vscode/IVSparse-Figures/plots/",name,"/","raw_",y_axis_variable,".pdf")
    path <- paste0("~/vscode/IVSparse-Figures/plots/",name,"/","raw_",y_axis_variable,".png")

    # png(file <- path,  
    # width = 6, # The width of the plot in inches
    # height = 6) # The height of the plot in inches
    
    png(filename = path,
        width = 6,
        height = 6,
        units = "in",
        res = 576 * 2
        # type = "Xlib"
        )
  
  
  # Select the first data point for each ID in eigenResults5, eigenResults10, and eigenResults3
  eigen_first_data_1 <- eigenResults1 %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable, rows, cols, nonzeros), ~ mean(., na.rm = TRUE))
  eigen_first_data_5 <- eigenResults5 %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~ mean(., na.rm = TRUE))
  eigen_first_data_10 <- eigenResults10 %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~ mean(., na.rm = TRUE))
  dataset1_first_data <- dataset1_results %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~ mean(., na.rm = TRUE))
  dataset2_first_data <- dataset2_results %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~ mean(., na.rm = TRUE))
  dataset3_first_data <- dataset3_results %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~ mean(., na.rm = TRUE))
  
  COO_size <- dataset3_results %>%
    group_by(ID) %>%
    summarise_at(vars(redundancy, y_axis_variable), ~ mean(., na.rm = TRUE))
  
  
  dense_size = ((eigen_first_data_1$rows * eigen_first_data_1$cols * 8) + (8 * eigen_first_data_1$rows) + 8)
  COO_size <- 16 * eigen_first_data_1$nonzeros / dense_size

  # Calculate the ratio by dividing y_axis_variable in dataset1_results by 16 * the corresponding values in eigen_first_data_1
  ratio1 <-
    dataset1_first_data[[y_axis_variable]] / dense_size
  # Calculate the ratio by dividing y_axis_variable in dataset2_results by 16 * the corresponding values in eigen_first_data_5
  ratio2 <-
    dataset2_first_data[[y_axis_variable]] / dense_size
  # Calculate the ratio by dividing y_axis_variable in dataset3_results by 16 * the corresponding values in eigen_first_data_10
  ratio3 <-
    dataset3_first_data[[y_axis_variable]] / dense_size
  # print(ratio2)
  
  # Combine the data frames for all three datasets and eigenResults
  combined_data <- rbind(
    data.frame(
      redundancy = dataset1_first_data$redundancy,
      ratio = ratio1,
      dataset = dataset1_name,
      eigenResult = "eigenResults1"
    ),
    data.frame(
      redundancy = dataset2_first_data$redundancy,
      ratio = ratio2,
      dataset = dataset2_name,
      eigenResult = "eigenResults5"
    ),
    data.frame(
      redundancy = dataset3_first_data$redundancy,
      ratio = ratio3,
      dataset = dataset3_name,
      eigenResult = "eigenResults10"
    ),
    data.frame(
      redundancy = dataset3_first_data$redundancy,
      ratio = COO_size,
      dataset = "COO",
      eigenResult = "eigenResults10"
    )
  )
  # Convert the dataset variable to a factor and set custom levels to control the order of appearance
  combined_data$dataset <-
    factor(combined_data$dataset,
           levels = c(dataset1_name, dataset2_name, dataset3_name, "COO"))
  # Reorder the ratio variable based on the order of appearance of data sets
  combined_data$ratio <- with(combined_data, ratio[order(dataset)])
  # Create the scatter plot for the dataset ratio over Eigen
  
    if (grepl("All", name, ignore.case = TRUE)) {
    name <- ""
    legend_name <- "Format"
    
    } else {
      name <- paste0(name, " ")
      legend_name <- "Density"
    }
  
  
p <- ggplot(combined_data, aes(x = redundancy, y = ratio, color = dataset, linetype = dataset)) +
    geom_line(size = 1.2) +
    labs(x = "Mean Matrix Redundancy",
         y = paste0("Ratio of ", name, " Memory Usage Over Dense")) +
    theme_minimal() +
    theme(axis.title.y = element_text(size = 18),
          axis.title.x = element_text(size = 18),
          axis.text = element_text(size = 18),
          legend.text = element_text(size =18),    # Adjust the font size of legend labels
          legend.title = element_text(size = 18)) +  # Adjust the font size here
    scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_color_manual(values = c("#00C058", "#BF00F1", "#0000EE", "#006f23"), 
                       labels = c(dataset1_name, dataset2_name, dataset3_name, "COO"), 
                       name = legend_name, 
                     guide = guide_legend(override.aes = list(size = 3), title = "Format: ")) + 
    scale_linetype_manual(values = c("solid", "dashed", "dotted", "dotdash"), 
                          labels = c(dataset1_name, dataset2_name, dataset3_name, "COO"), 
                          name = legend_name, 
                     guide = guide_legend(override.aes = list(size = 3), title = "Format: ")) + 
  theme( # All legend colors are made white as to be invisible. This keeps spacing for when there is a legend present -> all plots have the same dimension/layout
    legend.direction = "horizontal", 
    legend.text.align = 0.5, 
    legend.position = "bottom", 
    legend.spacing.x = unit(0.5, "mm"),
    legend.text = element_text(size = 18, color = "black"),  # Set legend text color
    legend.title = element_text(size = 18, color = "black"))  # Set legend title color


  num_markers <- nrow(combined_data)
  cat("Number of markers:", num_markers, "\n")
  # Set colors and labels for the legend using scale_color_manual and scale_shape_manual

  
  print(p)
  dev.off()
}

# VCSCResults102 = read.csv("~/resultsFixed/VCSCResults_CSC.csv")
# eigenResults102 = read.csv("~/resultsFixed/EigenResults_CSC.csv")
# IVCSCResults102 = read.csv("~/resultsFixed/IVCSCResults_CSC.csv")


# triple_size_plot(IVCSCResults10, "IVCSC",  VCSCResults10, "VCSC", eigenResults10, "CSC" , eigenResults10, eigenResults10, eigenResults10 ,"All_10_density")
# triple_size_plot(IVCSCResults102, "IVCSC",  VCSCResults102, "VCSC", eigenResults102, "CSC" , eigenResults102, eigenResults102, eigenResults102 ,"new2_All_10_density")


```


```{R}

density_triple_size_plot <- function(dataset1_results, dataset1_name, dataset2_results, dataset2_name, dataset3_results, dataset3_name, name) {
  
  y_axis_variable <- "size"

    dir.create(file.path(paste0("~/vscode/IVSparse-Figures/plots/",name)), showWarnings = FALSE)
    # path <- paste0("~/vscode/IVSparse-Figures/plots/",name,"/","raw_",y_axis_variable,".pdf")
    path <- paste0("~/vscode/IVSparse-Figures/plots/",name,"/","raw_",y_axis_variable,".png")

    # png(file <- path,  
    # width = 6, # The width of the plot in inches
    # height = 6) # The height of the plot in inches
    
    png(filename = path,
        width = 6,
        height = 6,
        units = "in",
        res = 576 * 2
        # type = "Xlib"
        )
  
  
  # Select the first data point for each ID in eigenResults5, eigenResults10, and eigenResults3
  dataset1_first_data <- dataset1_results %>%
    group_by(ID) %>%
    summarise_at(vars(sparsity, y_axis_variable, nonzeros, rows, cols), ~ mean(., na.rm = TRUE))
  dataset2_first_data <- dataset2_results %>%
    group_by(ID) %>%
    summarise_at(vars(sparsity, y_axis_variable, nonzeros), ~ mean(., na.rm = TRUE))
  dataset3_first_data <- dataset3_results %>%
    group_by(ID) %>%
    summarise_at(vars(sparsity, y_axis_variable, nonzeros), ~ mean(., na.rm = TRUE))
  
  # Calculate the new ratios based on the modified formula
  # dense_size = (10000 * 100 * 8) + (8 * 10000) + 8 # rows * cols * value_type + pointer_size * rows + pointer_pointer_size 
  dense_size = ((dataset1_first_data$rows * dataset1_first_data$cols * 8) + (8 * dataset1_first_data$rows) + 8)
  COO_size <- 16 * dataset1_first_data$nonzeros / dense_size

  new_ratio1 <- dataset1_first_data[[y_axis_variable]] / dense_size
  new_ratio2 <- dataset2_first_data[[y_axis_variable]] / dense_size
  new_ratio3 <- dataset3_first_data[[y_axis_variable]] / dense_size
  
  # Combine the data frames for all three datasets and eigenResults using the new ratios
  combined_data <- rbind(
    data.frame(
      sparsity = 1 - dataset1_first_data$sparsity,
      ratio = new_ratio1,
      dataset = dataset1_name
    ),
    data.frame(
      sparsity = 1 - dataset2_first_data$sparsity,
      ratio = new_ratio2,
      dataset = dataset2_name
    ),
    data.frame(
      sparsity = 1 - dataset3_first_data$sparsity,
      ratio = new_ratio3,
      dataset = dataset3_name
    ),
    data.frame(
      sparsity = 1 - dataset1_first_data$sparsity,
      ratio = COO_size,
      dataset = "COO"
    )
  )
  
  # Convert the dataset variable to a factor and set custom levels to control the order of appearance
  combined_data$dataset <-
    factor(combined_data$dataset,
           levels = c(dataset1_name, dataset2_name, dataset3_name, "COO"))
  # Reorder the ratio variable based on the order of appearance of data sets
  combined_data$ratio <- with(combined_data, ratio[order(dataset)])
  
  print(combined_data)
  
    if (grepl("All", name, ignore.case = TRUE)) {
    name <- ""
    legend_name <- "Format"
    
    } else {
      name <- paste0(name, " ")
      legend_name <- "Density"
    }
  

p <- ggplot(combined_data, aes(x = sparsity, y = ratio, color = dataset, linetype = dataset)) +
    geom_line(size = 1.2) +
    labs(x = "Sparsity",
         y = paste0("Ratio of ", name, " Memory Usage Over Dense")) +
    theme_minimal() +
    theme(axis.title.y = element_text(size = 15),
          axis.title.x = element_text(size = 18),
          axis.text = element_text(size = 18),
          legend.text = element_text(size = 18),
          legend.title = element_text(size = 18)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + # Set limits to start from 0.1
    scale_x_continuous(breaks = scales::pretty_breaks(n = 5)) +
    scale_color_manual(values = c("#00C058", "#BF00F1", "#0000EE", "#007058"), labels = c(dataset1_name, dataset2_name, dataset3_name, "COO"), name = legend_name) +
    scale_linetype_manual(values = c("solid", "dashed", "dotted", "dotdash"), labels = c(dataset1_name, dataset2_name, dataset3_name, "COO"), name = legend_name) +   
    theme(
      legend.direction = "horizontal", 
      legend.text.align = 0.5, 
      legend.position = "bottom", 
      legend.spacing.x = unit(0.5, "mm"))

  
  # myManual <- ggplot(combined_data, aes(x = redundancy, y = ratio, color = dataset, shape = dataset)) +
  #   geom_point() +
  #   labs(x = "Redundancy",
  #        y = paste0("Ratio of Memory Usage Over COO")) +
  #   theme_minimal() +
  #   theme(axis.title.y = element_text(size = 8),
  #         axis.title.x = element_text(size = 8)) +  # Adjust the font size here
  #   scale_color_manual(values = c("#00C058", "#BF00F1", "#0000EE"), labels = c(dataset1_name, dataset2_name, dataset3_name), name = "Format") +
  #   scale_shape_manual(values = c(16, 17, 15), labels = c(dataset1_name, dataset2_name, dataset3_name), name = "Format") +   theme(
  #     legend.direction = "horizontal", legend.text.align = 0.5)
  # 
  
  # Add a label "1.0" on the y-axis at y=1
  # if (!grepl("All", name, ignore.case = TRUE)) {
  #   p <- p + geom_hline(yintercept = 1,
  #                       color = "blue",
  #                       linetype = "solid")
  # }
  # # Count the number of markers (data points)
  num_markers <- nrow(combined_data)
  cat("Number of markers:", num_markers, "\n")
  # Set colors and labels for the legend using scale_color_manual and scale_shape_manual

  
  # Extract the legend separately using cowplot::get_legend()
  # legend <- get_legend(myManual)
  
  
  # Arrange the plots and the legend in a grid with one row and two columns
  # final_plot <- plot_grid(
  #   p,
  #   plot_grid(legend, ncol = 1, align = 'v'),  # Use 'v' for vertical center alignment
  #   ncol = 2,
  #   rel_heights = c(1, 1)
  # )
  # 
  # Print the final combined plot with a single legend beside the plots
  print(p)
  dev.off()
}

density_triple_size_plot(density_IVCSCResults10, "IVCSC",  density_VCSCResults10, "VCSC", density_eigenResults10, "CSC" ,"All_10_redundancy")


```

## **10% Dense**

```{R}
triple_size_plot(IVCSCResults10, "IVCSC",  VCSCResults10, "VCSC", eigenResults10, "CSC" , eigenResults10, eigenResults10, eigenResults10 ,"All_10_density")
triple_plot_ratio_over_eigen_no_legend(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"constructor_time","All_10_density")
triple_plot_raw(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"constructor_time","All_10_density")
triple_plot_ratio_over_eigen_no_legend(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"scalar_time","All_10_density")
triple_plot_ratio_over_eigen_no_legend(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"spmv_time","All_10_density")
triple_plot_ratio_over_eigen_bottom_legend(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"spmv_time","All_10_density")
triple_plot_ratio_over_eigen_no_legend(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"spmm_time","All_10_density")
triple_plot_ratio_over_eigen_bottom_legend(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"transpose_time","All_10_density")
triple_plot_raw(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"transpose_time","All_10_density")
triple_plot_raw(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"iterator_time","All_10_density")
triple_plot_ratio_over_eigen_bottom_legend(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"iterator_time","All_10_density")

triple_plot_ratio_over_eigen_no_legend(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"sum_time","All_10_density")
```
```{r}
triple_plot_raw(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"scalar_time","raw_All_10_density")
triple_plot_raw(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"spmv_time","raw_All_10_density")
triple_plot_raw(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"spmm_time","raw_All_10_density")
triple_plot_raw(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"constructor_time","raw_All_10_density")
triple_plot_raw(IVCSCResults10, "IVCSC", VCSCResults10, "VCSC", eigenResults10, "Eigen" ,eigenResults10, eigenResults10, eigenResults10 ,"iterator_time","raw_All_10_density")
triple_size_plot(IVCSCResults10, "IVCSC",  VCSCResults10, "VCSC", eigenResults10, "CSC" , eigenResults10, eigenResults10, eigenResults10 ,"raw_All_10_density")
# density_triple_size_plot(density_IVCSCResults10, "IVCSC",  density_VCSCResults10, "VCSC", density_eigenResults10, "CSC" ,"raw_All_10_density")


```


```{r}
library(dplyr)
library(ggplot2)

VCSCResults102 = read.csv("~/results/VCSCResults_COO.csv")
eigenResults102 = read.csv("~/results/EigenResults_COO.csv")
IVCSCResults102 = read.csv("~/results/IVCSCResults_COO.csv")

# VCSCResults102 = read.csv("~/resultsSPMM/VCSCResults_CSC.csv")
# eigenResults102 = read.csv("~/resultsSPMM/EigenResults_CSC.csv")
# IVCSCResults102 = read.csv("~/resultsSPMM/IVCSCResults_CSC.csv")

triple_plot_raw(IVCSCResults102, "IVCSC", VCSCResults102, "VCSC", eigenResults102, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"scalar_time","old_VCSC")
triple_plot_raw(IVCSCResults102, "IVCSC", VCSCResults102, "VCSC", eigenResults102, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"spmv_time","old_VCSC")
# triple_plot_raw(IVCSCResults102, "IVCSC", VCSCResults102, "VCSC", eigenResults102, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"spmm_time","old_old_VCSC")
triple_plot_raw(IVCSCResults102, "IVCSC", VCSCResults102, "VCSC", eigenResults102, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"constructor_time","old_VCSC")
triple_size_plot(IVCSCResults102, "IVCSC",  VCSCResults102, "VCSC", eigenResults102, "CSC" , eigenResults102, eigenResults102, eigenResults102 ,"old_VCSC")
triple_plot_raw(IVCSCResults102, "IVCSC", VCSCResults102, "VCSC", eigenResults102, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"iterator_time","old_VCSC")
triple_plot_raw(IVCSCResults102, "IVCSC", VCSCResults102, "VCSC", eigenResults102, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"transpose_time","old_VCSC")
# triple_size_plot(IVCSCResults102, "IVCSC",  VCSCResults102, "VCSC", eigenResults102, "CSC" , eigenResults102, eigenResults102, eigenResults102 ,"old_VCSC")
# density_triple_size_plot(density_IVCSCResults10, "IVCSC",  density_VCSCResults10, "VCSC", density_eigenResults10, "CSC" ,"raw_All_10_density")


```


```{r}


triple_plot_raw(largeIVCSCResults10, "IVCSC", largeVCSCResults10, "VCSC", largeEigenResults10, "Eigen" , largeEigenResults10, largeEigenResults10, largeEigenResults10 ,"iterator_time","large_All_10_density")


```

## Combined Plots

```{R}

VCSCResultsMAP = read.csv("~/resultsMAP/VCSCResults_COO.csv")
eigenResultsMAP = read.csv("~/resultsMAP/EigenResults_COO.csv")
IVCSCResultsMAP = read.csv("~/resultsMAP/IVCSCResults_COO.csv")

VCSCResultsO = read.csv("~/resultsOriginalVCSC/VCSCResults_COO.csv")
eigenResultsO = read.csv("~/resultsOriginalVCSC/EigenResults_COO.csv")
IVCSCResultsO = read.csv("~/resultsOriginalVCSC/IVCSCResults_COO.csv")


triple_plot_raw(VCSCResultsMAP, "VCSC - map", VCSCResultsO, "VCSC - array", eigenResultsO, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"scalar_time","VCSC_comp")
triple_plot_raw(VCSCResultsMAP, "VCSC - map", VCSCResultsO, "VCSC - array", eigenResultsO, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"spmv_time","VCSC_comp")
# triple_plot_raw(IVCSCResults102, "IVCSC", VCSCResults102, "VCSC", eigenResults102, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"spmm_time","old_old_VCSC")
triple_plot_raw(VCSCResultsMAP, "VCSC - map", VCSCResultsO, "VCSC - array", eigenResultsO, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"constructor_time","VCSC_comp")
triple_size_plot(IVCSCResultsO, "IVCSC",  VCSCResultsO, "VCSC - array", eigenResultsO, "CSC" , eigenResults102, eigenResults102, eigenResults102 ,"VCSC_comp")
triple_plot_raw(VCSCResultsMAP, "VCSC - map", VCSCResultsO, "VCSC - array", eigenResultsO, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"iterator_time","VCSC_comp")
triple_plot_raw(VCSCResultsMAP, "VCSC - map", VCSCResultsO, "VCSC - array", eigenResultsO, "Eigen" ,eigenResults102, eigenResults102, eigenResults102 ,"transpose_time","VCSC_comp")
# triple_size_plot(IVCSCResults102, "IVCSC",  VCSCResults102, "VCSC", eigenResults102, "CSC" , eigenResults102, eigenResults102, eigenResults102 ,"VCSC_comp")
# density_triple_size_plot(density_IVCSCResults10, "IVCSC",  density_VCSCResults10, "VCSC", density_eigenResults10, "CSC" ,"raw_All_10_density")



```


